declaraciones/api/urls.py
from django.conf.urls import url
from django.urls import path, reverse_lazy, re_path
from django.views.decorators.csrf import csrf_exempt
from rest_framework_simplejwt import views as jwt_views
from .views import declaraciones_api_view, \
test_protected_view, LoginView, ApiSimpleExample, OauthDeclaraciones

urlpatterns = [
    path("v2/jwt_declaraciones/", declaraciones_api_view),
    path("testview/", test_protected_view),
    path("oauthExample/", ApiSimpleExample),
    path("v2/declaraciones/", csrf_exempt(OauthDeclaraciones.as_view())),
    path('token/', LoginView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
]

declaraciones/declaraciones/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, re_path
from django.conf.urls import include, url
from declaracion import urls
from sitio import urls
from api import urls


urlpatterns = [
    path('', include('sitio.urls')),
    path('admin/', admin.site.urls),
    path('declaracion/', include('declaracion.urls')),
    path('api/', include('api.urls')),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

# front-edit
urlpatterns += [
    url(r'^front-edit/', include('front.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

admin.site.site_header = 'Administración de Declaraciones'
admin.site.site_title = 'Administración de Declaraciones'
admin.site.index_title =  'Bienvenido a la administración del sistema'

declaraciones/declaracion/models/informacion_personal.py
import uuid
from django.contrib.auth.models import User
from django.db import models
from django.db.models import CASCADE
from django.urls import reverse_lazy
from smart_selects.db_fields import ChainedForeignKey

from .catalogos import (CatPaises, CatEstadosCiviles,
                        CatTiposDeclaracion, CatRegimenesMatrimoniales,
                        CatGradosAcademicos, CatEstatusEstudios,
                        CatDocumentosObtenidos, CatEntesPublicos,
                        CatOrdenesGobierno,CatSectoresIndustria,
                        CatFuncionesPrincipales, CatAmbitosLaborales,
                        CatTiposRelacionesPersonales, CatPoderes,
                        CatTipoPersona, CatEntidadesFederativas, CatTipoVia,
                        CatMunicipios, CatMonedas,CatTiposOperaciones,CatEstatusDeclaracion,CatPuestos)
from django.db.models.signals import post_delete
from django.dispatch import receiver

#Se agrego variable global para los campos de modelos que lo necesiten ya que la informaciòn es la misma
TIPO_OPERACION = [
    ('AGREGAR', 'Agregar'),
    ('MODIFICAR', 'Modificar'),
    ('SIN_CAMBIO', 'Sin cambio'),
    ('BAJA', 'Baja')
]


class InfoPersonalFija(models.Model):
    """
    En este modelo se guarda la información personal del declarante
    """
    nombres = models.CharField(max_length=255, blank=True)
    apellido1 = models.CharField(max_length=255, blank=True)
    apellido2 = models.CharField(max_length=255, blank=True)
    curp = models.CharField(max_length=255, blank=True)
    puesto = models.CharField(max_length=255, blank=True)
    rfc = models.CharField(max_length=255, blank=True)
    telefono = models.CharField(max_length=14, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True, null=True)
    cat_ente_publico = models.ForeignKey(CatEntesPublicos, on_delete=models.DO_NOTHING, blank=True, null=True)
    cat_entidades_federativas = models.ForeignKey(CatEntidadesFederativas, on_delete=models.DO_NOTHING, null=True, blank=True)
    nombre_ente_publico = models.CharField(max_length=300, null=True, blank=True)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    cat_pais = models.ForeignKey(CatPaises, on_delete=models.DO_NOTHING, null=True, blank=True)
    otro_ente = models.CharField(max_length=255, blank=True, null=True)
    fecha_inicio = models.DateField(blank=True, null=True)

    def nombre_completo(self):
        return u"{} {} {}".format(self.nombres, self.apellido1,self.apellido2)



class Declaraciones(models.Model):
    """
    Modelo que guarda información de la declaración
    """
    folio = models.UUIDField(primary_key=False, default=uuid.uuid4, editable=False)
    fecha_recepcion = models.DateTimeField(blank=True, null=True)
    fecha_declaracion = models.DateField(null=True, auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    cat_tipos_declaracion = models.ForeignKey(CatTiposDeclaracion, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_estatus = models.ForeignKey(CatEstatusDeclaracion, on_delete=models.DO_NOTHING, default=1)
    avance = models.IntegerField(blank=True,default=0)
    info_personal_fija = models.ForeignKey(InfoPersonalFija, on_delete=models.DO_NOTHING)
    sello = models.TextField(blank=True)
    datos_publicos = models.BooleanField(blank=True, null=True, default=0)


class Domicilios(models.Model):
    """
    Modelo que guarda información de los domicilios
    ---------
    Debido a que existen multiples personas relacionadas que se crearán en la declaración 
    muchas contarán con direcciones propias(ej. Dependientes economicos)
    """
    cp = models.CharField(max_length=255, blank=True)
    colonia = models.CharField(max_length=255, blank=True)
    nombre_via = models.CharField(max_length=255, blank=True)
    num_exterior = models.CharField(max_length=255, blank=True)
    num_interior = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    cat_entidades_federativas = models.ForeignKey(CatEntidadesFederativas, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_pais = models.ForeignKey(CatPaises, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_tipo_via = models.ForeignKey(CatTipoVia, on_delete=models.DO_NOTHING, null=True, blank=True)
    municipio = models.ForeignKey(CatMunicipios, on_delete=models.DO_NOTHING,blank=True, null=True)
    ciudadLocalidad = models.CharField(max_length=100, blank=True, null=True)
    estadoProvincia = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        ordering=('pk',)

    def __str__(self):
        try: 
            return self.nombre_via + self.num_exterior + self.num_interior + self.colonia + self.cp  
        except:
            return "Domicilio"


class Observaciones(models.Model):
    """
    Modelo que guarda las observaciones por secciones
    """
    observacion = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.observacion


class InfoPersonalVar(models.Model):
    """
    Modelo que guarda información de multiples personas relacionadas a una declaración del declarante
    ---------
    Uso principal: Guarda información de
                                        -Pareja
                                        -Dependientes economicos
                                        -Empresa
                                        -Cliente
                                        -Etc, Más en el catálogo tipoPersona
    """
    TIPO_DECLARANTE = 1
    TIPO_DEPENDIENTE = 2
    TIPO_EMPRESA = 3
    TIPO_SOCIO = 4
    TIPO_CLIENTE = 5
    TIPO_SOCIEDAD = 6
    TIPO_INSTITUCION = 7
    TIPO_FIDEICOMISARIO = 8
    TIPO_FIDEICOMITENTE = 9
    TIPO_FIDUCIARIO = 10
    TIPO_COPROPIETARIO = 11
    TIPO_PROPIETARIO_ANTERIOR = 12
    TIPO_PRESTATARIO = 13
    es_fisica = models.BooleanField(blank=True, null=True, default=None)
    razon_social = models.CharField(max_length=255, blank=True, null=True)
    nombres = models.CharField(max_length=255, blank=True)
    apellido1 = models.CharField(max_length=255, blank=True)
    apellido2 = models.CharField(max_length=255, blank=True)
    curp = models.CharField(max_length=255, blank=True)
    rfc = models.CharField(max_length=255, blank=True)
    homoclave = models.CharField(max_length=3, blank=True, null=True)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    num_id_identificacion = models.CharField(max_length=255, blank=True)
    email_personal = models.CharField(max_length=255, blank=True)
    tel_particular = models.CharField(max_length=255, blank=True)
    tel_movil = models.CharField(max_length=255, blank=True)
    cat_entidades_federativas = models.ForeignKey(CatEntidadesFederativas, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_estados_civiles = models.ForeignKey(CatEstadosCiviles, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_pais = models.ForeignKey(CatPaises, on_delete=models.DO_NOTHING, null=True, blank=True)
    cat_regimenes_matrimoniales = models.ForeignKey(CatRegimenesMatrimoniales, on_delete=models.DO_NOTHING, null=True, blank=True)
    declaraciones = models.ForeignKey(Declaraciones, on_delete=models.DO_NOTHING)
    domicilios = models.ForeignKey(Domicilios, on_delete=models.DO_NOTHING, blank=True, null=True)
    observaciones = models.ForeignKey(Observaciones, on_delete=models.DO_NOTHING, blank=True, null=True)
    cat_tipo_persona = models.ForeignKey(CatTipoPersona, on_delete=models.DO_NOTHING, blank=True, null=True)
    cat_sectores_industria = models.ForeignKey(CatSectoresIndustria, on_delete=models.DO_NOTHING, blank=True, null=True)
    otro_sector = models.CharField(max_length=255, blank=True, null=True)
    otro_estado_civil = models.CharField(max_length=255, blank=True, null=True)
    actividad_economica = models.CharField(max_length=255, blank=True, null=True)
    ocupacion_girocomercial = models.CharField(max_length=255, blank=True, null=True)
    nombre_negocio = models.CharField(max_length=255, blank=True, null=True)
    rfc_negocio = models.CharField(max_length=50, blank=True, null=True) #/AGREGADO
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    nacionalidades = models.ManyToManyField(CatPaises, through='Nacionalidades', related_name="info_personal_var_nacionalidaes", blank=True)
    activos_bienes = models.ManyToManyField(
        'ActivosBienes',
        through='BienesPersonas',
        through_fields=('info_personal_var', 'activos_bienes'),
        related_name="info_personal_var_activos_bienes")


    class Meta:
        ordering=('pk',)

    def __str__(self):
        return self.rfc

    def nombre_completo(self):
        if self.es_fisica:
            return ("%s %s %s")%(self.nombres ,self.apellido1,self.apellido2)
        else:
            return self.razon_social

    def domicilio(self):
        return [self.domicilios]

    def observacion(self):
        return [self.observaciones]

    def nacionalidad(self):
        try:
            return self.nacionalidades.all()
        except:
            return None

    def tipo(self):
        return self.cat_tipo_persona_id

    def sectores_industrias(self):
        try:
            if self.cat_sectores_industria.default:
                return u"{} {}".format(self.cat_sectores_industria,
                                       self.otro_sector)
            else:
                return u"{}".format(self.cat_sectores_industria)
        except Exception as e:
            return u""


class Nacionalidades(models.Model):

declaraciones/declaracion/models/secciones.py
import uuid
from django.db import models
from .informacion_personal import(Declaraciones, Observaciones)
from mptt.models import MPTTModel, TreeForeignKey


class SeccionDeclaracion(models.Model):
    """
    Class Modelo que guarda información de la relación declaración-sección


    Methods
    -------------
    secciones_items(self)
        Retorna str de los items totales por secciones y cuales ya han sido registrados
    """
    PENDIENTE = 0
    COMPLETA = 1
    INCOMPLETA = 2
    STATUS_CHOICES = (
        (PENDIENTE, 'Pendiente'),
        (COMPLETA, 'Completa'),
        (INCOMPLETA, 'Incompleta'),
        )
    declaraciones = models.ForeignKey(Declaraciones,
                                    on_delete=models.CASCADE)
    seccion = models.ForeignKey('Secciones',
                                on_delete=models.CASCADE,
                                related_name='status')
    estatus = models.IntegerField(default=PENDIENTE, choices=STATUS_CHOICES)
    observaciones = models.ForeignKey(Observaciones,
                                      on_delete=models.CASCADE,
                                      verbose_name="",
                                      null=True,
                                      default=None)
    aplica = models.BooleanField()
    max = models.IntegerField(default=1)
    num = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def secciones_items(self):
        return "{}/{}".format(self.num,self.max)

class Secciones(MPTTModel):
    """
    Class Model que guarda información de las secciones de la declaración
    ----------
    En este modelo se crean los registros de las secciones que serán mostradas en pantalla del lado izquierdo a modo de acordeon

    Methods
    -------------
    get_status(self,folio)
        Se encarga de obtener el avance de la sección, es decir si los campos obligatorios han sido guardados retorna el str correspondiente
        En la parte izquierda de los formularios de la declaración (menú) existe al final de cada nombre de sección un punto rojo, palomita o signo de admiración
        dependiendo de la información retornada se muestran estos tres iconos
    """
    seccion = models.CharField(max_length=255)
    url = models.CharField(max_length=255, blank=True)
    parametro = models.CharField(max_length=255, blank=True, default='')
    order = models.IntegerField(default=1)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    def get_status(self, folio):
        try:
            folio = uuid.UUID(folio)
        except:
            return ('', '')
        declaracion = Declaraciones.objects.filter(folio=folio).first()

        try:
            status = SeccionDeclaracion.objects.filter(seccion=self).filter(declaraciones=declaracion).first()
            if status is None:
                return ('','')
            if status.num==0:
                return ('','')
            elif status.num == status.max:
                return ('success',"100%")
            elif status.num < status.max:
                return ('in-progress', str(status.num)+"/"+str(status.max) )
            else:
                return ('','')
        except:
            return ('', '')

    def __str__(self):
        return self.seccion

class CatCamposObligatorios(models.Model):
    """
    Class Modelo que guarda información sobre los campos que serán requiridos como obligatorios por sección
    ----------
    Este modelo se utiliza también para determinar aquellos campos que serán privados
    ----------
    No todos las campos por sección son agregados 
    """
    seccion = models.ForeignKey(Secciones, models.DO_NOTHING, blank=True, null=True)
    nombre_tabla = models.CharField(max_length=255, blank=True, null=True)
    nombre_columna = models.CharField(max_length=255, blank=True, null=True)
    es_obligatorio = models.IntegerField(blank=True, null=True)
    es_principal = models.BooleanField(default=False)
    esta_pantalla = models.BooleanField(default=False)
    tipo = models.IntegerField(default=0)
    es_privado =  models.BooleanField(default=False)

declaraciones/declaracion/forms/confirmacion.py
from django import forms
from django.core.validators import FileExtensionValidator


class ConfirmacionForm(forms.Form):
   datos_publicos = forms.TypedChoiceField(
                    coerce=lambda x: x == 'True',
                    choices=((False, 'False'), (True, 'True')),
                    widget=forms.RadioSelect,
                    required=True
                   )

declaraciones/declaracion/forms/ingresos.py
from bootstrap_datepicker_plus import DatePickerInput
from django import forms
from django.forms import  TextInput,Textarea
from declaracion.models import IngresosDeclaracion
import datetime

YEARS= [x for x in range(1940,datetime.date.today().year+1)]

class IngresosDeclaracionForm(forms.ModelForm):
    fecha_ingreso= forms.DateField(label='Fecha de nacimiento', widget=forms.SelectDateWidget(years=YEARS), required=False)
    fecha_conclusion= forms.DateField(label='Fecha de nacimiento', widget=forms.SelectDateWidget(years=YEARS),required=False)
    
    def __init__(self, *args, **kwargs):
        super(IngresosDeclaracionForm, self).__init__(*args, **kwargs)
        self.fields['ingreso_mensual_otros_ingresos'].widget.attrs['readonly'] = True
        self.fields['ingreso_mensual_neto'].widget.attrs['readonly'] = True
        self.fields['ingreso_mensual_pareja_dependientes'].widget.attrs['readonly'] = True
        self.fields['ingreso_mensual_total'].widget.attrs['readonly'] = True

    class Meta:
        model = IngresosDeclaracion
        fields = '__all__'
        exclude = ['declaraciones', 'observaciones']
        widgets = {
            'tipo_servicio': Textarea(attrs={'rows': 4})
        }

declaraciones/templates/declaracion/admin/acc_active_email_admin.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <style type="text/css">

        @import url('https://fonts.googleapis.com/css?family=Montserrat');

        .activa {
            width: 600px;
            height: 452px;
            margin: auto;
            text-align: center;
            font-family: Montserrat, sans-serif;
        }

        .HOLA {

            font-family: Montserrat, sans-serif;
            font-size: 20px;
            font-weight: bold;
            font-style: normal;
            font-stretch: normal;
            line-height: normal;
            color: #000000;
        }

        .cuenta {

            font-family: Montserrat, sans-serif;
            font-size: 14px;
            font-weight: normal;
            font-style: normal;
            font-stretch: normal;
            line-height: 1.71;
            color: #727176;
        }

        .texto {
            font-weight: bold;
            color: #31b700;
        }

        .click {
            color: #ffffff;
            text-decoration: none;
        }

        .pega {

            font-size: 14px;
            font-weight: bold;
            font-style: normal;
            font-stretch: normal;
            line-height: 1.71;
            text-align: center;
            color: #727176;
        }

        .rfc {

            font-family: Montserrat, sans-serif;
            font-size: 16px;
            font-weight: bold;

            color: #ff9914;
        }

        .Rectangle {
            width: 253px;
            height: 38px;
            border-radius: 4px;
            background-color: #ff9914;
            padding: 15px;
            text-decoration: none;
        }

        .GRACIAS {

            font-family: Montserrat, sans-serif;
            font-size: 20px;
            font-weight: bold;
            font-style: normal;
            font-stretch: normal;
            line-height: 1.2;
            text-align: center;
            color: #000000;
        }

    </style>
</head>
<body>

<div class="activa ">
    <img src="{{ protocol }}://{{ domain }}{% static 'src/img/logotipo-gobierno-cdmx-2.svg' %}"
         class="logotipo-gobierno-cdmx-2">
    <br/>
    <p class="HOLA"> HOLA {{ user.first_name|upper }} {{ user.last_name|upper }} </p>
    <p class="cuenta">Una cuenta de usuario ha sido creada para ti en el <span class="texto" >ADMINISTRADOR</span> DEL <span
            class="texto">SISTEMA DE DECLARACIONES DE LA CIUDAD DE MÉXICO</span>.</p><br/>

    <a href="{{ protocol }}://{{ domain }}{% url 'activar' uidb64=uid token=token %}" class="Rectangle"><span
            class="click">Haz click aquí para
        activarla</span></a><br/><br/>
    <p class="cuenta"><br/>Usuario: <span class="rfc">{{ user.username  }}</span><br></p>
    <p class="cuenta"><br/>Comtraseña: <span class="rfc">{{ password }}</span><br></p>
    <p class="cuenta">Al ingresar por primera vez, deberás cambiar tu contraseña.</p><br/>

    <p class="pega">O puedes copiar/pegar este enlace en el navegador: <br/><br/>
        <span> {{ protocol }}://{{ domain }}{% url 'activar' uidb64=uid token=token %}</span>
    </p>

    <p class="GRACIAS">¡GRACIAS!</p>
</div>
</body>
</html>

declaraciones/templates/declaracion/admin/busqueda-declaraciones.html
{% include 'layout/headertop.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
<form action="{% url 'declaracion:busqueda-declaraciones' %}" method="post" id="form_declaraciones">
  <section class="container">
    <div class="row row-md ">
      <h1 class="text-gray text-xl font-weight-medium text-uppercase mt-5 line-height-md title-mobile text-mobile"><span class="text-primary-light font-weight-semibold">
      DECLARACIONES</span> Búsqueda</h1>

      <div class="d-flex justify-content-center align-items-center flex-column flex-sm-row bg-gray p-4 rounded">
         {% csrf_token %}
         {%  bootstrap_field form.page %}
         <div class="row">
             <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
                 {% bootstrap_field form.folio  %}
             </div>
             <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
                 {% bootstrap_field form.tipo  field_class="solo_letras" %}
             </div>
              <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
                 {% bootstrap_field form.estatus %}
             </div>
              <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
                 {% bootstrap_field form.fecha_inicio %}
             </div>
             <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
                 {% bootstrap_field form.fecha_fin %}
             </div>
             <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4 ">
                 <button class="btn btn-success text-uppercase font-weight-semibold mt-5" type="submit" >Buscar  <img src="{% static 'src/img/busqueda.svg' %}"/></button>
                 &nbsp;&nbsp;&nbsp;
                 <a href="#" class="btn btn-success text-uppercase font-weight-bold mt-5" data-toggle="modal" data-target="#ventana-modal" target="_blank">Reportes   <img width="18px" src="{% static 'src/img/impresora_blanco.png' %}"/></a>
             </div>
         </div>
      </div>

    </div>
   {% if result %}
    <div class="row row-md">
      <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">FOLIO</th>
              <th scope="col">TIPO</th>
              <th scope="col">PORCENTAJE</th>
              <th scope="col">FECHA INICIO</th>
              <th scope="col">FECHA CIERRE</th>
              <th scope="col">ESTATUS</th>
              <th scope="col">VER</th>
            </tr>
          </thead>
          <tbody>
          {% for r in result %}
            <tr>
              <td scope="row">{{ r.folio }}</th>
              <td>{{ r.cat_tipos_declaracion.codigo }}</td>
              <td>{{ r.avance }}%</td>
              <td>{{ r.fecha_declaracion|date:"D d M Y"|default_if_none:"" }}</td>
              <td>{{ r.fecha_recepcion|date:"D d M Y"|default_if_none:"" }}</td>
              <td>{{ r.cat_estatus }}</td>
              <td><a href="{%  url 'declaracion:info-declaracion' r.pk 'declaracion' %}"> <img width="40px" src="{% static 'src/img/see_verde.png' %}"></a></td>
            </tr>
          {% endfor %}
          </tbody>
      </table>
    </div>

    <div class="row row-md text-center">
      <div class="col-12">
        <nav aria-label="Páginas" class="nav d-flex justify-content-center">
          <ul class="pagination flex-wrap">
          {% if result.has_previous %}
          <li class="page-item"><a class="page-link"  onclick="$('#id_page').val({{ result.previous_page_number }});$('#form_declaraciones').submit()" href="#">«</a></li>
           {% endif %}
                  {%for p in paginas%}
                    {%ifequal p result.number %}
                      <li class="page-item"><a class="page-link bg-primary text-light" href="#">{{result.number}}</a></li>
                    {%else%}
                      <li class="page-item"><a class="page-link"  onclick="$('#id_page').val({{ p }});$('#form_declaraciones').submit()" href="#">{{p}}</a></li>
                    {%endifequal%}
                  {%endfor%}
           {% if result.has_next %}
          <li class="page-item"><a class="page-link"  onclick="$('#id_page').val({{ result.next_page_number }});$('#form_declaraciones').submit()" href="#">»</a></li>
            {%endif%}

          </ul>
        </nav>
      </div>
    </div>
   {% else %}
      {% if messages %}
        <div class="row row-md">
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% else %}{{ message.tags }}{% endif %}{% endif %} col-12 text-center" role="alert"><h6>{{ message }}</h6></div>
          {% endfor %}
        </div>
        <br>
      {% endif %}
   {% endif %}
  </section>
</form>

<div class="modal fade" id="ventana-modal" tabindex="-1" role="dialog" aria-labelledby="lost-password-label" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="modal_logo"></div>
        <h4 class="modal-title" style="color: #A4B54C;">Click sobre botón para generar reporte</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <form action="#" method="get" id="form_declaraciones_reporte" target="_blank">
          <!--Se asignan los valores del formulario de busqueda a este formulario temporal para filtrar los datos en los reportes--->
          {% csrf_token %}
          <input type="hidden" name="folio" id="id_folio">
          <input type="hidden" name="tipo" id="id_tipo">
          <input type="hidden" name="estatus" id="id_estatus">
          <input type="hidden" name="fecha_inicio_day" id="id_fecha_inicio_day">
          <input type="hidden" name="fecha_inicio_month" id="id_fecha_inicio_month">
          <input type="hidden" name="fecha_inicio_year" id="id_fecha_inicio_year">
          <input type="hidden" name="fecha_fin_day" id="id_fecha_fin_day">
          <input type="hidden" name="fecha_fin_month" id="id_fecha_fin_month">
          <input type="hidden" name="fecha_fin_year" id="id_fecha_fin_year">

          <div class="image-title-wrap">
            <button type="submit" formaction="{% url 'declaracion:reporte' 'resumen_declaracion' %}" class="btn btn-outline-primary text-uppercase font-weight-bold" style="width: 330px;">
              <img style="max-height: 50px;max-width: 130px;" src="{% static 'src/img/pdf_bn.png'%}" alt="Descargar">Resumen por declaración
            </button>            
          </div>
          <div class="image-title-wrap">
            <button type="submit" formaction="{% url 'declaracion:reporte' 'completo_declaracion' %}" class="btn btn-outline-primary text-uppercase font-weight-bold" style="width: 330px;">
              <img style="max-height: 50px;max-width: 130px;" src="{% static 'src/img/pdf_bn.png'%}" alt="Descargar">Completo por declaración
            </button>            
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% include 'layout/footer.html' %}